FROM ise14.7-base
LABEL maintainer="Victor Muñoz <victor@2c-b.cl>"
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=ise14.7-builder /opt/Xilinx /opt/Xilinx

RUN cp /opt/Xilinx/14.7/ISE_DS/ISE/bin/lin64/xusbdfwu.hex /usr/share/ && \
    ln -s /opt/Xilinx/libXp.so.6.2.0 /usr/lib/x86_64-linux-gnu/libXp.so.6.2.0 && \
    ln -s /usr/lib/x86_64-linux-gnu/libXp.so.6.2.0 /usr/lib/x86_64-linux-gnu/libXp.so.6 && \
    ln -s libusb-1.0.so.0 /opt/Xilinx/14.7/ISE_DS/ISE/lib/lin64/libusb.so

# Final purge verification and removal of apt+dpkg tools
#RUN apt-get clean autoclean && apt-get autoremove --yes && \
#    rm -rf /var/lib/{apt,dpkg,cache,log}/
