FROM ubuntu:20.04 AS ise14-base
LABEL maintainer="Victor Muñoz <victor@2c-b.cl>"
ENV DEBIAN_FRONTEND=noninteractive

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get -y install \
    libusb-dev fxload \ 
    libsm6 libglib2.0-0 libxi6 libxrender1 libxrandr2 \
    libxtst6 \
    libfreetype6 libfontconfig1 gcc
RUN apt-get autoclean && apt-get autoremove --yes && \
    rm -rf /var/lib/apt/lists/*
